"""fix: task delete position

Revision ID: 2ee629b02068
Revises: 64f0d15b757c
Create Date: 2025-08-21 18:42:54.919972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee629b02068'
down_revision: Union[str, Sequence[str], None] = '64f0d15b757c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
