"""fix: task is_hidden

Revision ID: 64f0d15b757c
Revises: e2dd1deac68f
Create Date: 2025-08-20 11:04:17.859135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f0d15b757c'
down_revision: Union[str, Sequence[str], None] = 'e2dd1deac68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.drop_column('tasks', 'is_removed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_removed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'is_hidden')
    # ### end Alembic commands ###
