"""add task is_removed

Revision ID: e2dd1deac68f
Revises: 49bef6cf266a
Create Date: 2025-08-20 00:52:21.736563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dd1deac68f'
down_revision: Union[str, Sequence[str], None] = '49bef6cf266a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # 1. Добавляем новую колонку
  op.add_column(
    "tasks",
    sa.Column("new_id", sa.UUID(), nullable=False, server_default=sa.text("gen_random_uuid()"))
  )

  # 2. Убираем старый PK
  op.drop_constraint("tasks_pkey", "tasks", type_="primary")

  # 3. Делаем новый PK
  op.create_primary_key("tasks_pkey", "tasks", ["new_id"])

  # 4. Удаляем старую колонку
  op.drop_column("tasks", "id")

  # 5. Переименовываем новую колонку в id
  op.alter_column("tasks", "new_id", new_column_name="id")

  # 6. Добавляем новый столбец
  op.add_column('tasks', sa.Column('is_removed', sa.Boolean(), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('tasks', 'is_removed')
    # ### end Alembic commands ###
